services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    # Healthcheck para garantir que o serviço está totalmente pronto
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  collector:
    build: 
      context: ./python-collector
      dockerfile: Dockerfile
    env_file:
      - ./python-collector/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
